### ISSUE TITLE
Pinning package to repository?

### ISSUE THREAD

**Issue by zilti** [Malabarba/paradox#104]
Apparently, `package` offers the ability to pin a package to a certain repository with a line like 

```emacs-lisp
(add-to-list 'package-pinned-packages '(cider . "melpa-stable") t)
```

Could this be added to paradox as well? Also, it might be nice to allow for the inverse (whitelisting a repository only for certain packages).

**Comment by Malabarba** [comment]
Paradox is built on package.el. Anything that works on the latter works on the former. 😉

The white listing thing is a good idea, I'll try to think of a way to do it.

**Comment by Malabarba** [comment]
At least it should work. I just saw your comment and apparently it didn't work for you. 
I'll see if I can reproduce your problem.

**Comment by Malabarba** [comment]
I tried here, and this functionality works for me.
Could you try deleting cider, restarting emacs, and then installing it again? Maybe you were just a victim of some corner-case when you installed previously.

**Comment by Malabarba** [comment]
I tried here, and this functionality works for me.
Could you try deleting cider, restarting emacs, and then installing it again? Maybe you were just a victim of some corner-case when you installed previously.

**Comment by zilti** [comment]
Hm I now installed it manually (the package in question isn't updated often) and, since I switched over to use-package/req-package for "auto-installing" the packages am gonna wait for them to provide a fix (they have a bug concerning that). But thanks for investigating!
