### ISSUE TITLE
endlessly waiting github

### ISSUE THREAD

**Issue by tollerm** [Malabarba/paradox#105]
HI,
Since last 3 days paradox is endlessly waiting for sync with github showing the message:
"Contacting host: raw.githubusercontent.com: 443"

Best regards, Toller

**Comment by Malabarba** [comment]
It was a bug in a macro. Try restarting Emacs and then reinstalling paradox. What's your Emacs version?

**Comment by Poquaruse** [comment]
Same problem here. Version: GNU Emacs 25.0.50.1 (i686-pc-mingw32) of 2015-10-25

Reinstalling pardox didn't fix the problem.

**Comment by Malabarba** [comment]
@Poquaruse update to a more recent emacs snapshot

**Comment by tollerm** [comment]
Updating to the last Emacs and paradox solved the problem.
Thanks. Toller.

**Comment by Poquaruse** [comment]
Same for me. However, I had to delete all .el and .elc files in my .emacs.d, too.

Thanks!

(Guess this can be closed?!)

**Comment by Malabarba** [comment]
No problem. Closing!
