### ISSUE TITLE
filter for installed packages just like packages with upgrades.

### ISSUE THREAD

**Issue by HiCodin** [Malabarba/paradox#110]
is there anyway to filter just the installed packages just as `f u` to see packages with available updates ? 
I know i can just sort it to see the installed packages but is it possible to implement the feature ?

**Comment by Malabarba** [comment]
Filtering by package status has been implemented on the emacs 25 dev builds. I've added a `f i` key to paradox for filtering installed packages, but it will only show up for you if you use the dev builds.

Fortunately, emacs 25 shouldn't be too far now. :-)

**Comment by HiCodin** [comment]
i see. i'll just have to wait for the stable release of emacs 25 then. thanks for the reply. :+1:
