### ISSUE TITLE
Your Emacs snapshot is outdated

### ISSUE THREAD

**Issue by kaushalmodi** [Malabarba/paradox#113]
Hi,

I am on the latest commit from the emacs-25 branch and I still get that "outdated Emacs snapshot" message.

From the `paradox.el`, I see this:

```
  (when (and (fboundp 'package--update-downloads-in-progress)
             (not (fboundp 'package--with-response-buffer)))
    (message "[Paradox] Your Emacs snapshot is outdated, please install a more recent one."))
```

I see that in the latest snapshot, `package--update-downloads-in-progress` is in fact defined and there is no definition of `package--with-response-buffer` in `package.el`. So does that `when` form need updating?

**Comment by kaushalmodi** [comment]
I take that back.. some issue crept in my build process.. the package.el version in my git clone of emacs-25 is 1.1.0 but the version in the installed package.el.gz is 1.0.1! I'm not sure that caused that. But that definitely explains why that message is displayed.

**Comment by Malabarba** [comment]
No problem. :-)
Glad it's solved
