### ISSUE TITLE
Spinner 1.4 is unavailable in melpa, curent version is 1.7

### ISSUE THREAD

**Issue by DTDaschein** [Malabarba/paradox#114]
For those who are looking for one found available copy here
https://github.com/openprivacy/.emacs.d/tree/master/elpa/spinner-1.4

**Comment by Malabarba** [comment]
Specifying a spinner-1.4 dependency means that any version >= 1.4 is fine. So you should just install the most recent one.

Also, if you want a previous version of spinner, [GNU Elpa](http://elpa.gnu.org/packages/spinner.html) keeps all previous versions. (Although the site is down at the moment).

**Comment by DTDaschein** [comment]
Thanks for clarifying that. I use spacemacs so packages are autoloading in my case. Didn't even check elpa availability.
No longer had I problems when elpa went available)
