### ISSUE TITLE
Detect delete of package, dependent package in same transaction.

### ISSUE THREAD

**Issue by alflanagan** [Malabarba/paradox#117]
Just noticed that I had marked a package (svg-mode-line-themes) and its dependency (xmlgen) for deletion. This happened:

    Package transaction finished. Wed 23 Mar 2016 02:32:36 PM EDT
    Errors:
       (error Package ‘xmlgen-20130219.219’ is used by ‘svg-mode-line-themes’ as dependency, not deleting)

    Deleted:
        svg-mode-line-themes  20150425.1306

It would be nice if paradox detected the dependee being deleted, and didn't throw an error for the dependent.

**Comment by Malabarba** [comment]
Should be fixed now. Let me know if it works.
