### ISSUE TITLE
periodically check for updates in background and display in mode-line when available?

### ISSUE THREAD

**Issue by blaenk** [Malabarba/paradox#120]
This is a great package.

I was wondering if it would be possible to add functionality that checks for available package updates periodically in the background, and when there are any, display it in one's mode-line something like `package updates available: 4`.

Preferably I'd love it if this functionality were available in paradox, even if opt-in, and if it exposed a function so I could check if there are any so that I could expose the information in my mode-line how I see fit. Maybe there can be a function like `paradox-package-updates-available` which returns an integer, so usually it'd return 0. Then in the background, asynchronously, paradox would check for updates on some timer, say every 30 minutes or whatever, and updates the variable whose value the `paradox-package-updates-available` function returns. Then in my mode-line I'd just call that function to display that information however I want.

If you're not open to doing this, would you be kind enough to give me some pointers on how I may implement this myself? I'd truly appreciate it!

**Comment by blaenk** [comment]
Alright I see `paradox-refresh-upgradeable-packages` and `paradox--upgradeable-packages-number`, perhaps I can execute the former on some timer and then my mode-line can just use the latter to display its information. I recognize that the variable is private though, perhaps you'd be open to exposing it through a public function? I'll try it in the meantime though. I'd be interested in hearing your thoughts on this though, perhaps I'm going about it the wrong way.

**Comment by blaenk** [comment]
Nevermind I just realized that that function simply calls another which scans the package list buffer.

I think it's probably not possible to do what I'm asking because it seems that refreshing the package list is a synchronous operation.

**Comment by blaenk** [comment]
For the record the best I was able to come up with was a function which populates a temporary buffer with the package list and then uses the existing functions to scan to determine the number of upgradeable packages:

``` elisp
(defun blaenk/upgrades-count (&optional no-fetch)
  (interactive "P")
  (require 'finder-inf nil t)
  ;; Initialize the package system if necessary.
  (unless package--initialized
    (package-initialize t))
  (let (old-archives new-packages)
    (unless no-fetch
      ;; Read the locally-cached archive-contents.
      (package-read-all-archive-contents)
      (setq old-archives package-archive-contents)
      ;; Fetch the remote list of packages.
      (package-refresh-contents)
      ;; Find which packages are new.
      (dolist (elt package-archive-contents)
        (unless (assq (car elt) old-archives)
          (push (car elt) new-packages))))

    ;; Generate the Package Menu.
    (with-temp-buffer
      (package-menu-mode)
      (set (make-local-variable 'package-menu--new-package-list) new-packages)
      (package-menu--generate nil t)

      (let ((upgrades (package-menu--find-upgrades)))
        (if upgrades
            (length upgrades)
          0)))))
```

It works but it blocks all of emacs while it does "Connecting to melpa" etc.

**Comment by blaenk** [comment]
It looks like something like this may be possible in emacs 25

**Comment by Malabarba** [comment]
Hi there, sorry for taking long to reply. 
Yes, this should be possible in Emacs 25 thanks to async refreshing. However, it would need a bit of a smarter algorithm for determining the available upgrades. Something that doesn't rely on actually printing the packages buffer.
