### ISSUE TITLE
Sorting/Hidding package

### ISSUE THREAD

**Issue by Davidbrcz** [Malabarba/paradox#121]
Hello,

With MELPA enabled, there are more than 3000 packages available to install. IIt is a good thing to have that many packages, but is also clutter the interface.

I think It would be good to be able to hide some irrelevant packages (for instance, I don't care about javascript related packages) or to sort packages into category. 

David

**Comment by Malabarba** [comment]
Thanks for the suggestion. However, in Emacs 25 the package menu can hide packages (there's a command for that, but I forget the key it's bound to), so I won't be reimplementing that in Paradox.
