### ISSUE TITLE
Advices on package-* fn not effective when installing packages asynchronously

### ISSUE THREAD

**Issue by kaushalmodi** [Malabarba/paradox#123]
Hi Artur,

I am unable to understand why the below advice is effective when installing packages synchronously, but not when installed asynchronously.

```el
(defun modi/package-dependency-check-ignore (orig-ret)
  "Remove the `black listed packages' from ORIG-RET."
  (let ((pkg-black-list '(org))
        new-ret
        pkg-name)
    (dolist (pkg-struct orig-ret)
      (setq pkg-name (package-desc-name pkg-struct))
      (if (member pkg-name pkg-black-list)
          (message (concat "Package `%s' will not be auto-installed. "
                           "See `modi/package-dependency-check-ignore'.")
                   pkg-name)
        ;; (message "Package to be installed: %s" pkg-name)
        (push pkg-struct new-ret)))
    new-ret))
(advice-add 'package-compute-transaction :filter-return #'modi/package-dependency-check-ignore)
```

With the above evaluated, and `org` package deleted, if you install a package having `org` as dependency, like `ox-asciidoc`, the `org` package is not is auto-installed.

I use `org-mode` built from it's master branch. So I do not want to unnecessarily install it from Melpa/Org Elpa too.

This [emacs.SE][1] also explains this motivation.

Well, this solution works as long as I do not install an `org`-depending package asynchronously. So how can I make it work with async installs too?

Thanks.

[1]: http://emacs.stackexchange.com/q/26507/115

**Comment by Malabarba** [comment]
I sin

**Comment by Malabarba** [comment]
I don't think there's an easy way. You can't really advise a function that runs on a separate emacs process. The only way I can think of to solve your problem is to advise the function that produces the list of packages that need to be installed. This is called before forking off a second process, and you should be able to filter org from that list.

**Comment by kaushalmodi** [comment]
Thanks. I will try that out. Closing this issue.
