### ISSUE TITLE
paradox--package-homepage: Wrong type argument: hash-table-p, \224\275

### ISSUE THREAD

**Issue by mfiano** [Malabarba/paradox#124]
This seems to be random, but sometimes when I run paradox-list-packages I get this error:

```
paradox--package-homepage: Wrong type argument: hash-table-p, \224\275
```

and the resulting list of packages only has gnu-elpa sources (I'm using MELPA too).

Other times this does not error. Once it does error though, I have to kill emacs and hope for the best next session.

**Comment by babilen** [comment]
I just ran into the same issue and also had to kill emacs in order to get it running again.

This is with Emacs 25.1 and paradox 20161002.1154 within spacemacs.

**Comment by brunoqc** [comment]
I also had the same problem. It worked after I restarted emacs. I don't have spacemacs.

GNU Emacs 25.1.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.20.9) of 2016-09-18
paradox 20161002.1154

**Comment by areina** [comment]
Same issue here. 

```elisp
(defun paradox--package-homepage (pkg)
  "PKG can be the package-name symbol or a package-desc object."
  (let* ((object   (if (symbolp pkg) (cadr (assoc pkg package-archive-contents)) pkg))
         (name     (if (symbolp pkg) pkg (package-desc-name pkg)))
         (extras   (package-desc-extras object))
         (homepage (and (listp extras) (cdr-safe (assoc :url extras)))))
    (or homepage
        (and (setq extras (gethash name paradox--package-repo-list))
             (format "https://github.com/%s" extras)))))
```
In my case, `homepage` is nil, and the code is failing trying to access to `paradox--package-repo-list` because at that moment, it isn't a hash-table (the value is \224\275). What I'm not able to know is why the value of `paradox--package-repo-list` is that. 

It's failing with this pkg:
```
[cl-struct-package-desc zotxt (20161229 2233) "Tools to integrate emacs with Zotero via the zotxt plugin." ((request-deferred (0 2 0))) tar "melpa" nil nil nil]
```

**Comment by areina** [comment]
You can avoid the issue temporarily calling "paradox--refresh-remote-data", instead of restarting Emacs.

**Comment by Malabarba** [comment]
Paradox has been very stable for me over the last year, and this issue is now quite old. If anyone still has this problem, please open a new issue.
