### ISSUE TITLE
Access to paradox--upgradeable-package-number

### ISSUE THREAD

**Issue by jwintz** [Malabarba/paradox#132]
Hello,

Great package ! Using it so far as a replacement for the builtin `package.el`.

I would like to define a [spaceline](https://github.com/TheBB/spaceline#defining-a-segment) segment which displays the number of upgrades available.

Here is some code I start with in my `*scratch*` buffer using `M-x eval-buffer`, but with no success:

```
(require 'paradox)

(package-refresh-contents)

(message (format "%s" (paradox--upgradeable-packages-number)))
```

I get the error: `Symbol's function definition is void: paradox--upgradeable-packages-number`.

Paradox is the only package which provides such a variable, so I'm really eager to use it ;-)

Next step, will be to use the `async` package in order to not freeze the ui during `(package-refresh-contents)`, which I guess is mandatory for `paradox` to compute `paradox--upgradeable-packages-number`. 

Thanks.

  - ju

**Comment by Malabarba** [comment]
Just remove the parens around it. It's a variable, not a function. 😉

**Comment by jwintz** [comment]
My bad, of course it is a variable, still getting deep into Emacs Lisp Introduction and Reference manual ;-)

However, I had it working with the following snippet, not asynchronous unfortunately. Can't get access to `paradox--upgradeable-packages-number`.

```emacs-lisp
  (spaceline-define-segment prolusion-upgrades-count
    (when (string= major-mode "prolusion/dashboard-mode")
      (unless prolusion-upgrade-count
        (save-window-excursion
          (package-list-packages)
          (package-menu-mode)
          (setq prolusion-upgrade-count (length (package-menu--find-upgrades)))
          (kill-buffer (get-buffer "*Packages*"))))
      (if (> prolusion-upgrade-count 0)
          (format " %s" prolusion-upgrade-count))))
```
