### ISSUE TITLE
New packages functionality broken

### ISSUE THREAD

**Issue by renatofdds** [Malabarba/paradox#133]
Paradox used to display new packages as the packages which were never seen before from the fetched update list. Now it considers every package with an update as new, therefore losing the option to check out newly developed emacs packages. Is this intentional ?

Using GNU Emacs 25.1.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.22.5) of 2016-12-23

**Comment by Malabarba** [comment]
Strange. I'm relatively sure that it always used to list updates on that list. Maybe I'm going crazy,  though. :-)

**Comment by manuel-uberti** [comment]
I can't reproduce this.

**Comment by renatofdds** [comment]
Strange, it must have been some sort of setting that i used. You can close this since apparently it has nothing to do with paradox. I wonder what the setting was though, because that way i could see what were the new packages added. Maybe you can add a filter to recently-added (never seen) packages ?
