### ISSUE TITLE
Truly async upgrade-packages

### ISSUE THREAD

**Issue by sooheon** [Malabarba/paradox#137]
Even with `(setq paradox-execute-asynchronously t)`, `paradox-upgrade-packages` blocks all input for up to 10 seconds while it apparently attempts to contact the package archives. Can this not be sent to a background process? I'm sorry to make a feature request that I am not able to help implement in elisp myself, but it seems like pretty important functionality for a modern package manager.

**Comment by Malabarba** [comment]
I think it's already supposed to be on a background process. Are you sure that's the reason why it's hanging?

**Comment by noctuid** [comment]
This is the same problem mentioned in #120 I think.

**Comment by sooheon** [comment]
All I know is that with M-x paradox-upgrade-packages, emacs still hangs while the following prints in Messages:

```
Importing package-keyring.gpg...done
Contacting host: melpa.org:80 [2 times]
Contacting host: orgmode.org:80
Contacting host: raw.githubusercontent.com:443
```

Am I meant to get back non-blocking control immediately after invoking upgrade-packages?

**Comment by sooheon** [comment]
Starting with `emacs -Q`, initializing only `paradox`, and running `M-x paradox-update-packages` still has a long delay with no user input possible, displaying:

```
Importing package-keyring.gpg...done
Contacting host: elpa.gnu.org:80 [2 times]
```

`package-menu-async` is set to `t`.

I'm pretty sure it's just the contacting elpa.gnu.org:80 that takes time, but I think this blocking user input is a mistake.

**Comment by Malabarba** [comment]
Hm, which version of Emacs are you on? The actual upgrade procedure is made async by paradox, but the initial fetching of information is only async in Emacs 25.1 or above.

**Comment by noctuid** [comment]
I'm using emacs 26 (26.0.50.1), and this still happens for me. `paradox-upgrade-packages` explicitly sets `package-menu-async` to nil (9086bd2241f86488e816682af0ef9897569ab31b). Is this not the reason that the command blocks?

**Comment by Malabarba** [comment]
Oh dear, that's completely true. I should have looked at the function before replying to this issue. It's been a while since I wrote this.

Now I remember. `paradox-upgrade-packages` specifically disables `package-menu-async` simply because doing this operation after an asynchronous refresh would have taken a lot more work to implement.
So I suppose the answer is just: “Sorry, that's not supported.”
=/

**Comment by seagle0128** [comment]
Is there any setting to disable this behavior?
```
Contacting host: raw.githubusercontent.com:443
```

**Comment by Malabarba** [comment]
@seagle0128 You could hack it away like this:

```
(defun paradox--refresh-remote-data ()
  "STUB"
  nil)
```

**Comment by Malabarba** [comment]
Anyway, closing this issue as a "Won't do".
I'm happy to look at PRs if anyone wants to try.
