### ISSUE TITLE
Async update broken probably by a recent change in master (emacs 26.x)

### ISSUE THREAD

**Issue by kaushalmodi** [Malabarba/paradox#139]
The async update now gives error. I believe this started happening after one of the recent commits to the master branch within last 3-4 days:

Here is the error:

```
Debugger entered--Lisp error: (wrong-type-argument sequencep #s(package-desc swiper (20170328 737) "Isearch with an overview. Oh, man!" ((emacs (24 1)) (ivy (0 8 0))) nil nil "/home/kmodi/.emacs.d/elpa_26/swiper-20170328.737" ((:keywords "matching") (:url . "https://github.com/abo-abo/swiper") (:stars #("249" 0 3 (font-lock-face paradox-starred-face)))) nil))
  signal(wrong-type-argument (sequencep #s(package-desc swiper (20170328 737) "Isearch with an overview. Oh, man!" ((emacs (24 1)) (ivy (0 8 0))) nil nil "/home/kmodi/.emacs.d/elpa_26/swiper-20170328.737" ((:keywords "matching") (:url . "https://github.com/abo-abo/swiper") (:stars #("249" 0 3 (font-lock-face paradox-starred-face)))) nil)))
  async-handle-result((lambda (x) (setq package-alist (pop x) package-selected-packages (pop x) package-archive-contents (pop x)) (when (spinner-p paradox--spinner) (spinner-stop paradox--spinner) (setq paradox--spinner nil)) (setq paradox--executing nil) (run-hook-with-args (quote paradox-after-execute-functions) (pop x)) (paradox--post-execute-star-unstar (quote nil) (paradox--repo-alist))) (async-signal (wrong-type-argument sequencep #s(package-desc swiper (20170328 737) "Isearch with an overview. Oh, man!" ((emacs (24 1)) (ivy (0 8 0))) nil nil "/home/kmodi/.emacs.d/elpa_26/swiper-20170328.737" ((:keywords "matching") (:url . "https://github.com/abo-abo/swiper") (:stars #("249" 0 3 (font-lock-face paradox-starred-face)))) nil))) #<buffer *emacs*>)
```

Here is the recent commit log:

```
f1d34d9136 * master origin/master origin/HEAD Minor cleanups related to type-of
ab0a27517c * ; * lisp/emacs-lisp/package.el (describe-package-1): Tweak recent.
fe8cf45710 * * doc/lispref/package.texi (Package Archives): Mention https.
f981c611e2 * Advertise https for homepage of gnu.org packages
048133d488 * Default to https for elpa.gnu.org if gnutls available
82b9efc869 * Minor simplifications and doc for records
12317ff4fb * Fix recent changes in record data type
604eb02fff * Make subprocess functions resolve the default directory
f4b50dad8d * Make ediff handle remote and quoted file names
2c68192c6b * Backward compatibility with pre-existing struct instances.
b6738682ae * Make the URL library use records.
8e6f204f44 * Make EIEIO use records.
0565482838 * Make cl-defstruct use records.
a2c3343029 * Add record objects with user-defined types.
```

**Comment by kaushalmodi** [comment]
Pinging @larsbrinkhoff in case he has insight into this.

**Comment by cpitclaudel** [comment]
Looks like something in paradox was using a cl-defstruct as a sequence, but that breaks now?

**Comment by kaushalmodi** [comment]
@cpitclaudel `paradox` doesn't use `cl-defstruct`, but `package.el` does:

```
364:(cl-defstruct (package-desc
493:(cl-defstruct (package--bi-desc
1331:(cl-defstruct (package--ac-desc
```
.. and based on that backtrace, specifically:

```
364:(cl-defstruct (package-desc
```

Wondering though why this affects only async updates..

**Comment by npostavs** [comment]
Perhaps structures produced by `read` are no longer sequences? While structures produced by `make-foo` still are?

**Comment by larsbrinkhoff** [comment]
Thanks for the ping.  Yes, I feel responsible.

The problem is *probably* that some .elc file (package.elc) was compiled with the old cl-defstruct (or defclass).  Thus, there may be references to vectors or sequences which clash with the new record representation for structures and class instances.

**Comment by larsbrinkhoff** [comment]
We have tried to arrange for backward compatibility by providing `cl-old-struct-compat-mode`.  Calling that function with a positive number will help in some cases.

**Comment by larsbrinkhoff** [comment]
I see package.el defines `package--bi-dec` and `package--ac-desc` as `:type vector` structures.  But `package-desc` use the default, i.e. is was a vector and is now a record.

**Comment by larsbrinkhoff** [comment]
`paradox--menu-execute-1` calls `async-start` with two lambda functions.  The first lambda throws an error.  It's hard to say where this error comes from.  Maybe the call to `package-activate`.

Are you sure you have recompiled `package.elc`?  Please try to rebuild Emacs with `make bootstrap`.

**Comment by kaushalmodi** [comment]
> Are you sure you have recompiled `package.elc`? 

I did not confirm but I thought that should have happened because I did rebuild emacs with `make bootstrap`.

There was no option because before `make bootstrap`, I got:

```
Loading emacs-lisp/timer...
Loading isearch...
Attempt to autoload cl-old-struct-compat-mode while preparing to dump
make[1]: *** [emacs] Error 255
make[1]: Leaving directory `/home/kmodi/downloads/git/emacs/src'
make: *** [src] Error 2 
```

**Comment by larsbrinkhoff** [comment]
Ok great, in that case package.elc should be ok.

I would like to reproduce the error myself.  Which are the steps I need to do?

**Comment by larsbrinkhoff** [comment]
Async works by starting another Emacs process.  If this other Emacs would be an older version, that could be a problem.

**Comment by Malabarba** [comment]
Could it just be a case of reinstalling Paradox? Have you tried that @kaushalmodi? 
Reinstalling Paradox will recompile everything which might fix the issue (make bootstrap doesn't recompile stuff installed via elpa).

**Comment by larsbrinkhoff** [comment]
It could well be that reinstalling Paradox could solve the superficial problem.  But then we still haven't found the root cause.  We're supposed to be able to say `(cl-old-struct-compat-mode 1)` and have still .elc files work as before.

**Comment by kaushalmodi** [comment]
> Could it just be a case of reinstalling Paradox? Have you tried that @kaushalmodi?

Yes I have tried that, and also removing the .elc files. But none helped.

> We're supposed to be able to say (cl-old-struct-compat-mode 1) and have still .elc files work as before.

I haven't set that minor mode, but doing `C-h v cl-old-struct-compat-mode` says that the value is `t` and the default was `nil`. So got auto-enabled somewhere.. but still I get this issue.

---

I tried to recreate this issue in a sandbox environment using `emacs -Q`.. and I am unable to do that :(

So as @larsbrinkhoff mentioned, it probably some precompiled .elc in my elpa dir.

Here is my sandbox testing code.. anyone can try this quickly:

```el
;; This buffer is for text that is not saved, and for Lisp evaluation.
;; To create a file, visit it with C-x C-f and enter text in its buffer.

(defmacro emacs-pkg-debug-setup (pkg-alist &rest body)
  "Install packages in PKG-ALIST and evaluate BODY.
Each element of PKG-ALIST has the form (((ID . LOCATION) . (PKG1 PKG2 ..)) ..).
The ID and LOCATION are the same as the ones in `package-archives'.
PKG1, PKG2, .. are package names from the ID archive.

Example usage:

1. Launch 'emacs -Q'.
2. Copy this macro definition to its scratch buffer and evaluate it.
3. Evaluate a minimum working example using this macro as below:
     (emacs-pkg-debug-setup '(;; Install hydra from GNU Elpa
                              (nil . (hydra))
                              ;; Install org from Org Elpa
                              ((\"org\" . \"http://orgmode.org/elpa/\") . (org)))
       ;; Then evaluate the below forms
       (org-mode)) "
  (declare (indent 1) (debug t))
  `(progn
     (require 'package)
     (setq user-emacs-directory (concat temporary-file-directory
                                        (getenv "USER") "/" ".emacs.d-debug/"))
     (setq package-user-dir (format "%selpa_%s/"
                                    user-emacs-directory emacs-major-version))
     (let (archive pkgs)
       (dolist (archive-alist ,pkg-alist)
	 (setq archive (car archive-alist))
	 (when archive
           (add-to-list 'package-archives archive :append))
         (setq pkgs (append pkgs (cdr archive-alist))))
       (package-initialize)
       (package-refresh-contents)

       (dolist (pkg pkgs)
         (when (and pkg (not (package-installed-p pkg)))
           (package-install pkg))
         (require pkg))

       ,@body)))

(emacs-pkg-debug-setup '(;; Install paradox from Melpa
			 (("melpa" . "http://melpa.org/packages/") . (async spinner paradox)))
  ;; Then evaluate the below forms
  (require 'paradox)
  (setq paradox-execute-asynchronously t)
  (paradox-enable)
  (package-list-packages))      ;Now put the point on any package and do "i x y"
```

---

I will now copy my current elpa dir to a bkp, and force byte recompile that whole dir,and see if the issue still persists.

**Comment by kaushalmodi** [comment]
Force byte-recompiling the whole elpa dir did not help.. I'll now bisect my config to get to the bottom of this. It'll be strange if my config has anything to do with this as I never used `cl-defstruct` and similar forms.

**Comment by kaushalmodi** [comment]
>Force byte-recompiling the whole elpa dir did not help

I take that back.. partially.

After the force byte-recompiling of elpa dir.. I was able to install the `0xc` package, but then again when I attempted to upgrade the packages.. the earlier issue reoccurred and one of the dependent packages `spinner` started throwing errors:

```
Error during redisplay: (eval (spinner-print paradox--spinner)) signaled (wrong-type-argument spinner [cl-struct-spinner ["  " "▌ " "█ " "▐▌" " █" " ▐"] 0 10 [t nil nil nil nil nil nil nil nil] nil #<buffer *Packages*> 0])
Error during redisplay: (eval (spinner-print paradox--spinner)) signaled (wrong-type-argument spinner [cl-struct-spinner ["  " "▌ " "█ " "▐▌" " █" " ▐"] 0 10 [t nil nil nil nil nil nil nil nil] nil #<buffer *Packages*> 0]) [3 times]
QuitError during redisplay: (eval (spinner-print paradox--spinner)) signaled (wrong-type-argument spinner [cl-struct-spinner ["  " "▌ " "█ " "▐▌" " █" " ▐"] 0 10 [t nil nil nil nil nil nil nil nil] nil #<buffer *Packages*> 0])
Error during redisplay: (eval (spinner-print paradox--spinner)) signaled (wrong-type-argument spinner [cl-struct-spinner ["  " "▌ " "█ " "▐▌" " █" " ▐"] 0 10 [t nil nil nil nil nil nil nil nil] nil #<buffer *Packages*> 0]) [137 times]
3 packages marked for upgrading.
Error during redisplay: (eval (spinner-print paradox--spinner)) signaled (wrong-type-argument spinner [cl-struct-spinner ["  " "▌ " "█ " "▐▌" " █" " ▐"] 0 10 [t nil nil nil nil nil nil nil nil] nil #<buffer *Packages*> 0]) [42 times]
Install 3 packages, and Delete 3 packages? (y or n) y
Error during redisplay: (eval (spinner-print paradox--spinner)) signaled (wrong-type-argument spinner [cl-struct-spinner ["  " "▌ " "█ " "▐▌" " █" " ▐"] 0 10 [t nil nil nil nil nil nil nil nil] nil #<buffer *Packages*> 0]) [84 times]
Execute in the background (see `paradox-execute-asynchronously')? (y or n) y
Error during redisplay: (eval (spinner-print paradox--spinner)) signaled (wrong-type-argument spinner [cl-struct-spinner ["  " "▌ " "█ " "▐▌" " █" " ▐"] 0 10 [t nil nil nil nil nil nil nil nil] nil #<buffer *Packages*> 0]) [12 times]
error in process sentinel: async-handle-result: Wrong type argument: sequencep, #s(package-desc yaml-mode (20170213 1023) "Major mode for editing YAML files" ((emacs (24 1))) nil nil "/home/kmodi/.emacs.d/elpa_26/yaml-mode-20170213.1023" ((:stars #("206" 0 3 (font-lock-face paradox-starred-face))) (:keywords "data" "yaml")) nil)
error in process sentinel: Wrong type argument: sequencep, #s(package-desc yaml-mode (20170213 1023) "Major mode for editing YAML files" ((emacs (24 1))) nil nil "/home/kmodi/.emacs.d/elpa_26/yaml-mode-20170213.1023" ((:stars #("206" 0 3 (font-lock-face paradox-starred-face))) (:keywords "data" "yaml")) nil)
Error during redisplay: (eval (spinner-print paradox--spinner)) signaled (wrong-type-argument spinner [cl-struct-spinner ["  " "▌ " "█ " "▐▌" " █" " ▐"] 0 10 [t nil nil nil nil nil nil nil nil] nil #<buffer *Packages*> 0]) [1218 times]
Mark set
Error during redisplay: (eval (spinner-print paradox--spinner)) signaled (wrong-type-argument spinner [cl-struct-spinner ["  " "▌ " "█ " "▐▌" " █" " ▐"] 0 10 [t nil nil nil nil nil nil nil nil] nil #<buffer *Packages*> 0]) [4638 times]
```

I'll try removing `spinner` from paradox and see if the issue still occurs.

**Comment by larsbrinkhoff** [comment]
That macro looks great!  I'll try it soon.

**Comment by larsbrinkhoff** [comment]
Those latest error messages look interesting.  It seems that something (maybe paradox) is making old-style defstruct instances, i.e. `[cl-struct-spinner ...]`.  Something else is expecting new-style records.

**Comment by larsbrinkhoff** [comment]
@kaushalmodi So the .elc files in your sandboxed .emacs.d-debug work fine, but the ones in your real .emacs.d doesn't?  Then, what's the difference between the two?

**Comment by kaushalmodi** [comment]
There are 2 big variables there:

- My .emacs.d with all other packages installed too. The sandboxed area has only async, spinner and paradox.
- Also my whole config: But not yet sure how anything in my config can affect the cl-defstruct stuff.

Hopefully I can get some time tonight/tomorrow to play with those variables.

Also.. I normally (99.99% of the times) run emacsclient. The sandboxed emacs -Q launches emacs instead of emacsclient. I don't know if that has anything to do with this.

**Comment by kaushalmodi** [comment]
@larsbrinkhoff Yes! Finally able to recreate this issue in emacs -Q. Use the above macro definition and call. The issue pops up after the first or second installations are done.. odd.

1. Eval the above macro defn and call.. that will install the required packages and open paradoxified package-list-packages.
2. Put point on `0xc`, `i`; put point on `2048-game`, `i`,.. `x`, `y`... that installed those 2 packages fine.
3. Now put point on `4clojure`, `i`, `x`, `y`.. Boom!

```
Package refresh done
Install 2 packages? (y or n) y
Setting ‘package-selected-packages’ temporarily since "emacs -q" would overwrite customizations
Installed 2 packages. See the buffer *Paradox Report* for more details.
Install 1 package? (y or n) y
Setting ‘package-selected-packages’ temporarily since "emacs -q" would overwrite customizations
error in process sentinel: if: Wrong type argument: sequencep, #s(package-desc 4clojure (20131014 1507) "Open and evaluate 4clojure.com questions" ((json (1 2)) (request (0 2 0))) single "melpa" nil ((:stars "") (:keywords "languages" "data")) nil)
```

So after the first install.. something corrupts the internal state of the defstruct datatypes or something?

**Comment by larsbrinkhoff** [comment]
Confimed!  I see the same thing.  Thanks for sticking with this.  I'll try to look into it tomorrow.

**Comment by kaushalmodi** [comment]
> Confimed!

Phew :) Thank you!

**Comment by kaushalmodi** [comment]
@larsbrinkhoff BTW after a recompilation of my whole elpa, things are falling apart.. (glad I made a backup)

```
magit-insert-unstaged-changes: Wrong type argument: magit-section, [cl-struct-magit-section unstaged nil #<marker at 498 in *magit: .emacs.d> nil nil nil nil nil nil ...]
```

**Comment by larsbrinkhoff** [comment]
That's an instance of the structure `magit-section`.  It looke like magit isn't recompiled properly.

Is there any chance that recompiling or reinstalling packages makes .elc files with the wrong Emacs version?  Just grasping for staws here.

**Comment by larsbrinkhoff** [comment]
Using @kaushalmodi's sandboxed test, I see that paradox-execute.elc has suspect content.  There are references to `cl-struct-package-desc-tags`.

Ah!  async-bytecomp.elc also has those.  Maybe recompiling files asynchrously brings in old definitions?

**Comment by larsbrinkhoff** [comment]
It seems that every time you try to install new packages, the first install works fine (or doesn't display any errors), and the second install fails.  This still holds true if you exit Emacs and start again with the same .emacs.d-debug.

Oh, and I deleted my paradox-execute.elc.  Still works the same running the source .el I guess.

**Comment by larsbrinkhoff** [comment]
This turned out to be a problem with the read syntax for records, e.g. this failed

    (read "(#1=#s(foo) #1#)")

I have pushed a fix.  @kaushalmodi, please try it.

**Comment by kaushalmodi** [comment]
Oh, I so to rebuild Emacs right now with that fix. But unfortunately I have hit a logistic issue.. cannot VPN to my work machine (where I build Emacs) over the weekend. I do this first thing on Monday and confirm. 

Thanks!

**Comment by larsbrinkhoff** [comment]
No problem!

**Comment by kaushalmodi** [comment]
I confirm this fix @larsbrinkhoff. Thanks!

**Comment by larsbrinkhoff** [comment]
Great!
