### ISSUE TITLE
Columns in package list are not aligned when native line numbers are enabled in Emacs.

### ISSUE THREAD

**Issue by vlichevsky** [Malabarba/paradox#144]
Columns don't line up when I turn on display of line numbers, a feature that was recently added to Emacs master.

Line numbers enabled, columns misaligned:
![line-numbers](https://user-images.githubusercontent.com/17594809/28073758-65d6b6ae-665f-11e7-87b8-b8bdb9fdbfec.png)

Line numbers disabled, everything is OK:
![no-line-numbers](https://user-images.githubusercontent.com/17594809/28073759-66249932-665f-11e7-8a86-0261efb4034d.png)

**Comment by Malabarba** [comment]
Thanks for the bug report. Have you checked if it also happens with the regular package menu?

**Comment by vlichevsky** [comment]
Yes, indeed, regular package menu has the same problem. The bug seems to be not with the paradox package.
Line numbers:
![package-line-numbers](https://user-images.githubusercontent.com/17594809/28107830-0ba7af42-66f2-11e7-98a9-5b03fc0c278a.png)

No line numbers:
![package-no-line-numbers](https://user-images.githubusercontent.com/17594809/28107849-1e661ae2-66f2-11e7-8884-8522d87b12a6.png)

**Comment by Malabarba** [comment]
Ok, looks like a bug with tabulated-list-mode then. Could you open a bug report with emacs devel?
