### ISSUE TITLE
Paradox not catching some errors properly 

### ISSUE THREAD

**Issue by heikkil** [Malabarba/paradox#145]
I ran command paradox-upgrade-packages and got this report:

```
Package transaction finished. Fri Jul 14 14:56:53 2017
Errors:
  (file-error https://melpa.org/packages/markdown-mode-20170712.1703.el Bad Request)


Installed:
  with-editor       20170707.1401
  web-mode          20170709.922
  w3m               20170714.1117
  use-package       20170710.1234
  undo-tree         20170706.246
  suggest           20170703.1433
  ssh-config-mode   20170711.1433
  powerline         20170708.1442
  pass              20170712.33
  package-lint      20170709.120
  org-ref           20170707.1048
  org-plus-contrib  20170710
  org               20170710
```
In less than an hour, I ran the same command again. This time markdown-mode-20170712.1703 and a large number of other packages were installed. The new report also included the deleted list for all the newly installed packages. The deleted packages that were supposed to be reported in the first upgrade were not removed from the file system. The printed file-error above was not caught properly and prevented the deletion.

**Comment by Malabarba** [comment]
Preventing the deletion is intentional. When paradox catchs an error during execution it stops execution and reports the error. That's because it would be really hard to figure out which of the remaining tasks are still safe to do after the error happens.

**Comment by heikkil** [comment]
Makes sense.
