### ISSUE TITLE
obsolete timestamp with cdr 51115

### ISSUE THREAD

**Issue by manuel-uberti** [Malabarba/paradox#154]
I am using latest `paradox` from MELPA. 

Whenever I do <kbd>M-x paradox-list-packages</kbd>, I get this message:

```
Error during redisplay: (eval (paradox--start-spinner)) signaled (wrong-type-argument number-or-marker-p 1.539069559218766e+21)
obsolete timestamp with cdr 51115
```

I can still upgrade packages successfully, but I was wondering what this could be related to. I don't see any errors with `toggle-debug-on-error` active.

Some information about my system, if it can be of any help:

```
GNU Emacs 27.0.50 (build 1, x86_64-debian-linux-gnu, GTK+ Version 3.22.30)
 of 2018-10-09

Repository revision: 333f0bfe766185c66952c6fbd4796c6bb97c868d
Configured using:
--host=x86_64-debian-linux-gnu --with-modules host_alias=x86_64-debian-linux-gnu

Emacs uptime: 1 hour, 19 minutes, 8 seconds
Colour theme: sanityinc-tomorrow-night
Operating system: Ubuntu 18.04.1 LTS
Window system: x11
Desktop environment: GNOME Shell 3.28.3
```

**Comment by Malabarba** [comment]
Alright. Keep me informed!

**Comment by manuel-uberti** [comment]
I rebuilt Emacs `master`, after cleaning `/etc/emacs` and `/usr/share/emacs`, but the message is still there. Still working on it, but could be something on Emacs `master`.

**Comment by manuel-uberti** [comment]
I wiped out my configuration, and recreated it, but this the error remains. This is weird stuff indeed! :)

**Comment by Malabarba** [comment]
A true Halloween mistery!

**Comment by rprimus** [comment]
Tue Oct 16 10:40:23 BST 2018

It may be related to emacs commit: [d80a09](https://git.savannah.gnu.org/gitweb/?p=emacs.git;a=commit;h=93fe420942c08111a6048af7c4d7807c61d80a09)

```
    New (TICKS . HZ) timestamp format
```

**Comment by manuel-uberti** [comment]
Nice find, @rprimus!

It's definitely something on `master`, because the same setup I use doesn't throw error messages on a colleague's Emacs 26.1.

**Comment by kaushalmodi** [comment]
@manuel-uberti I am seeing this too. This and deadgrep packages are affected by that timestamp change (of the packages that I use).

**Comment by kaushalmodi** [comment]
This issue is fixed in Emacs master. Build using the [efb214622 / Oct 20, 2018][0] commit or later.

[0]: https://git.savannah.gnu.org/cgit/emacs.git/commit/?id=efb214622a0f4e077c09e721d134552dfe76ef70

**Comment by manuel-uberti** [comment]
```
GNU Emacs 27.0.50 (build 1, x86_64-debian-linux-gnu, GTK+ Version 3.22.30)
 of 2018-10-22

Repository revision: 969b561972527b0471f9d1b29e0190e978ad8bc1
Configured using:
--host=x86_64-debian-linux-gnu --with-modules
```

Still seeing the message.

**Comment by kaushalmodi** [comment]
I built using:

> Emacs version: GNU Emacs 27.0.50 (build 31, x86_64-pc-linux-gnu, GTK+ Version 2.24.23)
 of 2018-10-22, built using commit 7d5919e5e73c62735297eb118b913029594bd0ef.

The spinner is now working for me:

![paradox_spinner](https://user-images.githubusercontent.com/3578197/47305184-ae6f4900-d5f6-11e8-86ee-7600c26ba6a8.gif)

**Comment by manuel-uberti** [comment]
The spinner works for me too, but the message is still there.

**Comment by kaushalmodi** [comment]
@manuel-uberti Try this latest commit: https://git.savannah.gnu.org/cgit/emacs.git/commit/?id=8602bd855904acc1966f1a94a008f91bb3f88c18 (I am perplexed why I don't see those messages even before applying that commit).

**Comment by manuel-uberti** [comment]
Yes, the message is gone now. Thanks for the tip.
