### ISSUE TITLE
Diff - Inspect updated parts before accepting

### ISSUE THREAD

**Issue by eubarbosa** [Malabarba/paradox#158]
Letting users inspect what have been changed on packages updates is a crucial feature.

Maybe is beyond Paradox way of updating packages, still...

That is it! :D

**Comment by Malabarba** [comment]
If you hit `l` on a package you'll get a list of commits since your currently installed version. Hitting return on a commit will visit it on github.

Have fun. 😀

**Comment by eubarbosa** [comment]
Valeu!
