### ISSUE TITLE
Errors: (wrong-type-argument stringp (require . info))

### ISSUE THREAD

**Issue by wdenton** [Malabarba/paradox#162]
Recently I stopped being able to update all packages at once.  Now "U x y" updates one package, throws an error, then stops, so I need to update each one individually.

The Paradox Report buffer always says:

    Package transaction finished. Wed 30 Jan 2019 10:50:40 AM EST
    Errors:
      (wrong-type-argument stringp (require . info))
 
I don't know if this is happening in Paradox or it's something else that's sending its problem to Paradox.

This is on Emacs 27.0.50, compiled fresh from the source.

**Comment by Malabarba** [comment]
It looks like the package is throwing an error during installation, and paradox is just reporting that error.
Regretably, it seems that paradox isn't smart enough to tell you which package caused the problem. :-(
