### ISSUE TITLE
Filter by keyword minimum version phrasing

### ISSUE THREAD

**Issue by duianto** [Malabarba/paradox#164]
These two lines:
```
    * `f k` filters by keyword (emacs 24.4 only).
```
https://github.com/Malabarba/paradox/blame/798bdabdca6575d677631b1c482e975c9372d536/README.md#L74

and

https://github.com/Malabarba/paradox/blob/e5dd26f67ba8fa8ab1631a00ddea4117805b3fd0/paradox.el#L42

most likely mean that the `filter by keyword` feature only works with a minimum Emacs version of `24.4`. But the text `only` makes it sound like it only works with that specific version.

Maybe they should say `(emacs 24.4+)`, or something better.

**Comment by Malabarba** [comment]
Thanks for pointing that out. Fixed it by just removing it because we only support 24.4+ anyway
