### ISSUE TITLE
Package nil is not a GitHub repo.

### ISSUE THREAD

**Issue by hmelman** [Malabarba/paradox#167]
I do paradox-list-packages, put point on a package line for a package (e.g., counsel, avy, ivy) and hit l and I see a message "Package nil is not a GitHub repo." If it hit return I see the info window appear and the homepage is listed as github.

**Comment by yuhan0** [comment]
Same here, since a week ago or so the majority of packages no longer have Github repo associations or star counts in the paradox-menu packages buffer. The main reason I use Paradox is to view commit logs, which no longer works either.

**Comment by Malabarba** [comment]
Thanks for the report.
Yes, I can confirm that too. Haven't managed to look into it yet.

**Comment by Malabarba** [comment]
Ok, I see what's causing the problem. I was generating the data without using a token, so I was hitting github API's rate limits.

Can you restart Emacs and see if the problem is solved?

**Comment by hmelman** [comment]
It seems to be fixed!

**Comment by Malabarba** [comment]
Great!

**Comment by slumos** [comment]
I'm having this problem. Restarting did not help. Also regenerated my token before searching issues.
