### ISSUE TITLE
paradox-previous-entry: No more buttons

### ISSUE THREAD

**Issue by manuel-uberti** [Malabarba/paradox#170]
Hi,

with latest `paradox` form MELPA, I cannot use <kbd>p</kbd> in `paradox-list-packages`. I get the message `No more buttons`. I can still use <kbd>C-p</kbd> (`previous-line`).

This is happening with `emacs -Q` too.

Here some details about my configuration:

```
GNU Emacs 27.0.50 (build 1, x86_64-debian-linux-gnu, GTK+ Version 3.22.30)
 of 2019-04-15

Repository revision: da3e3fc7971eab2391a745d9429c6c70bc70e27c
Configured using:
--host=x86_64-debian-linux-gnu --with-modules host_alias=x86_64-debian-linux-gnu

Emacs uptime: 51 minutes, 43 seconds
Colour theme: zenburn
Operating system: Ubuntu 18.04.2 LTS
Window system: x11
Desktop environment: GNOME Shell 3.28.3
```

If you need more details or further tests, feel free to ask.

**Comment by Malabarba** [comment]
I'm experiencing it too, but I think it might be an Emacs bug. Paradox
hasn't changed this kind of stuff in a while, and I also get a different
error in forward-button.
It warrants more invetigation before submitting a proper bug though.

>

**Comment by kaushalmodi** [comment]
I am on emacs master branch too, and I noticed this today. Enabling debug-on-error gives this on hitting `n` (and similar error on `p`):

```
Debugger entered--Lisp error: (error "Variable binding depth exceeds max-specpdl-size")
  get-char-property(18644 button)
  button-at(18644)
  next-button(18560)

  ...

  next-button(2229)
  next-button(2214)
  next-button(2212)
  forward-button(1)
  paradox-next-entry(1)
  funcall-interactively(paradox-next-entry 1)
  call-interactively(paradox-next-entry nil nil)
  command-execute(paradox-next-entry)
```

**Comment by kaushalmodi** [comment]
A wild guess .. may be this new error is related to https://git.savannah.gnu.org/cgit/emacs.git/commit/?id=08235af38c92e95d8ec9d268916d8910ea50ab2d ?

/cc @basil-conto

**Comment by basil-conto** [comment]
Sounds likely. My patch could have exposed a bug in either `button.el` or how `paradox` uses the library. I'll have a look in a bit.

**Comment by basil-conto** [comment]
I think I have spotted the problem: `paradox` is trying to emulate `button.el` buttons by manually propertizing strings with the `button` property, rather than using the `button.el` API. I consider this a bug with `paradox` and will try to send in a PR fixing it soon.

**Comment by manuel-uberti** [comment]
Thanks for debugging this, guys.

**Comment by basil-conto** [comment]
> I consider this a bug with `paradox` and will try to send in a PR fixing it soon.

I submitted #171 for your consideration.
