### ISSUE TITLE
Is it possible to defer this package with use-package?

### ISSUE THREAD

**Issue by fetatefog** [Malabarba/paradox#173]
I am trying to defer this package during startup as:
```
(use-package paradox
:ensure t
:defer t )
```

but when i call package-list-package, there is no paradox at all. So, is it possible to defer this until i call package-list-package?

**Comment by Malabarba** [comment]
You can call paradox-list-package, that should take care of everything.

**Comment by testinggithub1222** [comment]
@Malabarba  thanks! It works perfect.

**Comment by Malabarba** [comment]
You're welcome. :)
