### ISSUE TITLE
Error in paradox-list-packages on emacs HEAD

### ISSUE THREAD

**Issue by jguenther** [Malabarba/paradox#175]
After [a6d87ea045](https://github.com/emacs-mirror/emacs/commit/a6d87ea045) with paradox enabled, `package--downloads-in-progress` is `(paradox--data)`, so package refresh always fails with `user-error: Package refresh is already in progress, please wait...`

**Comment by sewkokot** [comment]
I confirm that, after pulling the current emacs master branch, I get the same issue: `user-error: Package refresh is already in progress, please wait...`

**Comment by manuel-uberti** [comment]
Same happening here, thanks for the fix @jguenther.

**Comment by manuel-uberti** [comment]
@Malabarba do you think @jguenther's patch could be turned into a PR?

**Comment by jguenther** [comment]
@manuel-uberti unlikely IMO--that function is defined in emacs' package.el, doubtful a workaround specific to paradox would make it in there

**Comment by aladine** [comment]
I also have the same issue.
My Emacs version is 27, built on Mac OS.

**Comment by Malabarba** [comment]
It won't make it into Emacs, but we can certainly write a patch to use in Paradox.
I don't understand your code, though, @jguenther. What does `el-patch-swap` do?

**Comment by Malabarba** [comment]
Ah, I think I get it.
However, a more appropriate solution would be to figure out why `paradox--data` is not getting removed from the in-progress list.

**Comment by jguenther** [comment]
Yeah, `el-patch` is intended to be a "less hacky" way to override/hack a function temporarily, without risking a situation where you're overriding the function even though the upstream one has since changed.

You define what part of the fn to patch, and if the upstream changes that part of the function later on, you'll get a notification that it has changed when `el-patch` tries to apply the patch (hopefully because the upstream fixed it etc). This definitely shouldn't be the permanent fix, I posted it here as a temporary workaround until an actual fix is in place.

The alternative workaround would be to redefine the fn after the default one is loaded from package.el (but again this shouldn't IMO be the permanent fix)

i.e.
```lisp
(with-eval-after-load 'package
  (defun package-menu-refresh ()
    "Override package-menu-refresh to work around Malabarba/paradox#175"
    (interactive)
    (unless (derived-mode-p 'package-menu-mode)
      (user-error "The current buffer is not a Package Menu"))
    (when (and package-menu-async package--downloads-in-progress
               (seq-difference package--downloads-in-progress '(paradox--data)))
      (user-error "Package refresh is already in progress, please wait..."))
    (setq package-menu--old-archive-contents package-archive-contents)
    (setq package-menu--new-package-list nil)
    (package-refresh-contents package-menu-async)))
```

**Comment by vlichevsky** [comment]
Any progress on the issue?

**Comment by Malabarba** [comment]
I've pushed a commit that *might* fix the issue. Could you please see if it fixes it for you? (You'll need to wait an hour or two for Melpa to update)

**Comment by Malabarba** [comment]
Nevermind, I can see the issue is still happening.

**Comment by Malabarba** [comment]
Ok. This time I managed to reproduce and test locally. Sorry for the long delay in fixing this.
I've pushed a comit that raelly should fix it, please test in an hour or so and let me know if it works.

The problem was simply something that changed in package.el. `list-packages` was changed to error out if the list is already being refreshed. And the way paradox has always worked was that it starts refreshing its own data first (asynchronously) and then calls `list-packages`.
