### ISSUE TITLE
Filters break in emacs-27

### ISSUE THREAD

**Issue by franburstall** [Malabarba/paradox#181]
In a `*Packages*` buffer, I type `fi`.

What I expect: a filter applied to show just installed packages.

What I get: `Symbol’s function definition is void: package-menu-filter`.

Commentary: this is in emacs 27.0.91 where `package.el` has changed the name of `package-menu-filter` to `package-menu-filter-by-keyword` by the look of things.

**Comment by wyuenho** [comment]
It's still around, but it's obsoleted.

**Comment by franburstall** [comment]
Yup.  I don't get an error in 27.2.  Closing.
