### ISSUE TITLE
GitHub Integration

### ISSUE THREAD

**Issue by joca-bt** [Malabarba/paradox#23]
Every time I run `paradox-list-packages` it asks me for GitHub integration. I have set `(setq paradox-github-token nil)` to avoid this but with no avail. In fact, calling `paradox-list-packages` and replying no sets it to `t`.

**Comment by swarnendubiswas** [comment]
I am having a similar issue. Setting paradox-github-token to t via customize interface and saving it for future sessions don't seem to work. I keep getting the "do you want...?" message every time I start paradox.

My init.el contains (custom-set-variables '(paradox-github-token t)). Is this correct?

**Comment by joca-bt** [comment]
Weird, it should, try with ```(setq paradox-github-token t)```.

**Comment by Bruce-Connor** [comment]
@swarnendubiswas Try adding `(setq paradox-github-token t)` to your init file, as suggested by @joca-bt 

The custom-set-variables version should have worked, but the customize system is complicated and there are things which could get in the way.

**Comment by swarnendubiswas** [comment]
Thanks guys. Setting it with custom-set-variables do not work (I am not sure why), but `(setq paradox-github-token t)` in init works.
