### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by llcc** [Malabarba/paradox#52]
Hi @Bruce-Connor 

I can not install paradox from package-install. 
It gives me an error message:
```package-compute-transaction: Package `spinner-1.0' is unavailable```

**Comment by Bruce-Connor** [comment]
You probably don't have gnu-Elpa configured in your package-archives. 

How are your setting your package-archives variable?

**Comment by Bruce-Connor** [comment]
There's is probably a line somewhere in your `.emacs` (or your `init.el` file) referencing `package-archives`.  It should look something like this:

    (add-to-list 'package-archives ...)

It should **NOT** look like this

    (setq package-archives ...)

**Comment by Malabarba** [comment]
Hi @llcc , did this issue go away?

**Comment by llcc** [comment]
@Malabarba , really sorry to response late.
I think my problem had been solved by using `setq` to add GNU-elpa in to the package-archives. 
Yes, I agree with you, it is best to add it to the list, not just setq it one time.
Thanks for helping me.
