### ISSUE TITLE
Errors in process sentinel are unclear

### ISSUE THREAD

**Issue by alphapapa** [Malabarba/paradox#55]
I just upgraded some packages, and I got these errors:
```
Installed 71 packages, and Deleted 71 packages. See the buffer *Paradox Report* for more details.
error in process sentinel: cond: Github returned: HTTP/1.1 401 Unauthorized

error in process sentinel: Github returned: HTTP/1.1 401 Unauthorized
```
But the report buffer simply shows that the transaction completed.  I don't know if those errors caused any actual problems, and I don't know what packages or URLs caused the errors.

**Comment by Bruce-Connor** [comment]
If the report buffer shows no error, than the transaction was successful. 

The error you got is related to github. Do you have a github token configured? The error is saying your token is not authorized.

**Comment by alphapapa** [comment]
Well, I guess I've been staring at Emacs for too long, because my eyes jumped to the HTTP 401 and overlooked the "Github" part.  I guess I need to make a new token.  Sorry about that.

I don't know if it would be worth the trouble, but you might consider making the error message more specific, something like `GitHub API token rejected.  You need to get a new token.`

**Comment by Bruce-Connor** [comment]
It's a good idea. I'll leave this open until I have some time.
