### ISSUE TITLE
paradox--github-action: Invalid function: 204 

### ISSUE THREAD

**Issue by Mitchicus** [Malabarba/paradox#57]
paradox-version is: 2.1, emacs version is: 24.4.1.
I get this error whenever I attempt to star a package or look at the commit list for a package. It seems like it could be an error on my end since I don't see any relevant changes in the recent patch but just incase I'll put this here.

**Comment by Malabarba** [comment]
It seems to be any issue when trying to interact with the github API.

Does it happen with absolutely any package? Or just some (and it so, which are them)?
If it happens with any package you can try reconfiguring your github token.

**Comment by Mitchicus** [comment]
Yes, every package is affected. I just tried deleting my token and going through the whole process again but that didn't fix it. Not sure what may have caused this at all. I'll have another look at it tomorrow to see what's going on.

**Comment by Malabarba** [comment]
Ok. I've meaning to [make the github api errors more verbose](#55) anyway, so I'll to do that now and that should help us determine what's happening here.

**Comment by Malabarba** [comment]
Actually, now that I read it better, your issue has nothing to do with github.
I think something wrong happened last time you upgraded Paradox and an instance of the `cl-case` macro wasn't expanded correctly.

I'm not 100% sure why that happened to you, but I've pushed a commit which should avoid that happening.
After you upgrade again, let me know whether it's working or not for you.

**Comment by Mitchicus** [comment]
Well I just came home to my emacs and you seem to have fixed it for me haha. Thanks for the rapid response!
