### ISSUE TITLE
Paradox + smart-mode-line: counter not refreshed

### ISSUE THREAD

**Issue by manuel-uberti** [Malabarba/paradox#58]
I am using latest Paradox and smart-mode-line.
After I upgraded some packages the ```Upgrade``` counter in the mode line is not refreshed.

This is what I normally do:
- call ```paradox-list-packages```
- say I have two packages to upgrade (Mode line correctly say so). So I hit ```U``` and then ```x```
- wait for packages to be installed
- back to packages list
- ```Upgrade``` indicator in the mode line does not get updated

If you need me to do some other tests, feel free to ask.

**Comment by Malabarba** [comment]
Thanks for reporting. I think I've fixed the issue, let me know!

**Comment by manuel-uberti** [comment]
Yes, it is fixed now. Thank you.
