### ISSUE TITLE
Visit Weblink is not working

### ISSUE THREAD

**Issue by sarvex** [Malabarba/paradox#64]
Paradox show 'h' with links to github pages, but when i click the browser is not opened with the associated url

**Comment by Malabarba** [comment]
If you hit RET on the link, does it work?

**Comment by Malabarba** [comment]
Alright, the latest commit should make homepage buttons reactive to mouse-clicks.

**Comment by Malabarba** [comment]
Let me know if it works.

**Comment by sarvex** [comment]
:) its working now
