### ISSUE TITLE
Symbol's function definition is void: paradox--pdate-downloads-in-progress

### ISSUE THREAD

**Issue by manuel-uberti** [Malabarba/paradox#67]
Hi,

I got this when trying to call ```paradox-list-packages```:
```
error in process filter: Symbol's function definition is void: paradox--pdate-downloads-in-progress [2 times]
```
I am using latest Paradox from MELPA. If you need me to debug or do some other kind of tests, please feel free to ask.

**Comment by Malabarba** [comment]
Yes, it was a typo that I fixed a couple of hours ago (most recent commit) try again once Melpa updates.

**Comment by manuel-uberti** [comment]
You are right, error's gone.
However, this one turns out now in ```*Messages*```: ```[Paradox] Error downloading Github data```

**Comment by Malabarba** [comment]
Ok, I pushed a new commit which I think will fix this. Look for a Melpa upgrade in an hour or two and let me know if it worked.

**Comment by manuel-uberti** [comment]
Yes, fixed. Thank you, Artur.
