### ISSUE TITLE
Paradox buffer stays in the Upgrade list view after finishing the upgrades

### ISSUE THREAD

**Issue by kaushalmodi** [Malabarba/paradox#68]
I am on emacs 25.x and using the latest Paradox available on Melpa.

I upgrade the packages using the async option.

Earlier the view reverted to the package list after finishing the upgrades. But now the view still shows the upgrade list after finishing the upgrades. This problem started happening some time in the past 1 week probably.

For example: Below view is after `diff-hl` finished upgrading.

![clipboard01](https://cloud.githubusercontent.com/assets/3578197/7069598/a9602050-dea7-11e4-83e0-4aa15abdff3b.png)

**Comment by Malabarba** [comment]
Thanks for reporting. Should be fixed now.
