### ISSUE TITLE
Symbol's value as variable is void: spinner-types

### ISSUE THREAD

**Issue by manuel-uberti** [Malabarba/paradox#70]
I just grabbed latest Paradox from MELPA.
When calling ```paradox-list-packages```, this error shows up: ```Symbol's value as variable is void: spinner-types```.

I am using Emacs ```25.0.50.1``` on Debian unstable.

**Comment by Malabarba** [comment]
Sorry. Should be fixed now.

**Comment by manuel-uberti** [comment]
Yes, works good now. Thank you.
