### ISSUE TITLE
Paradox fails to complete update

### ISSUE THREAD

**Issue by boudiccas** [Malabarba/paradox#71]
Todays paradox package update fails when trying to update 'async' from 20150203 to 20150412. The new package is not downloaded and paradox just hangs and fails to complete. 

These packages are updated - auctex, evil, hydra, m-buffer, ido-ubiquitus, ido-completeing-read+, paradox, sx,  but the old packages have not yet been deleted. And a new package - per-buffer-theme has not yet been installed.

**Comment by Malabarba** [comment]
So the package that failed to update was the `async` package?

- What are the contents of your `*Paradox Report*` buffer? It should say something about the error.
- Could you try to update that package without using Paradox? To do that, simply:
   1. Restart emacs
   2. Run the regular `M-x list-packages` (instead of `paradox-list-packages`)
   3. Try to update the package and let me know if it worked

**Comment by boudiccas** [comment]
Artur Malabarba <notifications@github.com> writes:

> So the package that failed to update was the async package?
>
>   * What are the contents of your *Paradox Report* buffer? It
>   should say something about the error.

It does not create a *Paradox Report* buffer, its still churning
away and failing to complete. 

>   * Could you try to update that package without using Paradox? To do that, simply:
>      1. Restart emacs
>      2. Run the regular M-x list-packages (instead of paradox-list-packages)
>      3. Try to update the package and let me know if it worked

Yes, it worked and deleted the old package to my trash can, so it is
possible to examine it for forensic purposes if required. 

Thanks
Sharon.
-- 
A taste of linux = http://www.sharons.org.uk
TGmeds = http://www.tgmeds.org.uk
Debian testing, fluxbox 1.3.7, emacs 24.4.1.0

**Comment by Malabarba** [comment]
I suspect this was a bug in async. Looking at their commit lists, there is an entry yesterday saying:

     * async-bytecomp.el (package--compile): Fix typo.

Maybe this typo is what caused your failed installation.
Since you said you still have the old directory in your trash bin, could you restore it and try to upgrade it again with Paradox?

Before you do the upgrade invoke `M-x toggle-debug-on-error`, so if you get the error again Emacs will display a backtrace (but make sure you run the upgrade synchronously).

**Comment by boudiccas** [comment]
Artur Malabarba <notifications@github.com> writes:

> I suspect this was a bug in async. Looking at their commit lists, there is an entry yesterday saying:
>
>  * async-bytecomp.el (package--compile): Fix typo.
>
> Maybe this typo is what caused your failed installation.
> Since you said you still have the old directory in your trash bin, could you restore it and try to upgrade it again with Paradox?
>
OK, restored, and paradox buffer now shows -

--8<---------------cut here---------------start------------->8---
  async            h 20150203… obsolete              184  Asynchronous processing in Emacs 

  async            h 20150412… installed             184  Asynchronous processing in Emacs 
--8<---------------cut here---------------end--------------->8---

So I then deleted "20150412" which then showed "20150203" as being
"installed".

Then I did an update which deleted "20150203" and installed
"20150412" with no problems.

--8<---------------cut here---------------start------------->8---
Package transaction finished. Tue 14 Apr 2015 13:46:30 BST
Deleted:
  async  20150412.2207



Package transaction finished. Tue 14 Apr 2015 13:47:38 BST
Installed:
  async  20150412.2207

Deleted:
  async  20150203.2127
--8<---------------cut here---------------end--------------->8---

I have still got "async  20150203.2127" saved away from the
executable path, so its possible to restore it again for further
testing.

This is from my "init.org" -

--8<---------------cut here---------------start------------->8---
*** Paradox
# #+BEGIN_SRC emacs-lisp
#   (use-package async
#     :ensure t)

#   (use-package paradox
#     :ensure t
#     :config
#     (setq paradox-execute-asynchronously t))
# #+END_SRC
[2015-03-29 Sun 14:19]

#+begin_src emacs-lisp
(require 'paradox)
#+end_src
[2015-04-14 Tue 13:37]
--8<---------------cut here---------------end--------------->8---

Thanks
Sharon.

> Before you do the upgrade invoke M-x toggle-debug-on-error, so if you get the error again Emacs will display a backtrace (but make sure you run the upgrade
> synchronously).
>
-- 
A taste of linux = http://www.sharons.org.uk
TGmeds = http://www.tgmeds.org.uk
Debian testing, fluxbox 1.3.7, emacs 24.4.1.0

**Comment by Malabarba** [comment]
Ok
All this data points towards an issue with async after all.
I'll close the issue for now. Let me know if it happens again.
