### ISSUE TITLE
Symbol's value as variable is void: \.async

### ISSUE THREAD

**Issue by sebastiencs** [Malabarba/paradox#72]
Hello,

Every time I download a new package I got this error:

```
error in process sentinel: run-hook-with-args: Symbol's value as variable is void: \.async
error in process sentinel: Symbol's value as variable is void: \.async

**Comment by Malabarba** [comment]
For some reason paradox did not install correctly. Try reinstalling, and pay attention to any messages during installation.

**Comment by sebastiencs** [comment]
Thanks, it works now.
