### ISSUE TITLE
Required package `spinner-1.0' is unavailable

### ISSUE THREAD

**Issue by expez** [Malabarba/paradox#74]
```
Warning (emacs): Unable to activate package `paradox'.
Required package `spinner-1.0' is unavailable
```
```elisp
(setq package-archives '(("melpa" . "http://melpa.org/packages/" )
                         ("marmalade" . "http://marmalade-repo.org/packages/")
                         ("elpy" . "http://jorgenschaefer.github.io/packages/")
                         ("gnu" . "http://elpa.gnu.org/packages/"))
      package-enable-at-startup nil)
```
What gives?

**Comment by Malabarba** [comment]
How did you install paradox?

**Comment by expez** [comment]
This problem occurred when I updated paradox this morning.  Everything is installed using the package manager.

**Comment by Malabarba** [comment]
Odd

**Comment by Malabarba** [comment]
Is spinner installed? What happens if you try to require 'spinner?

**Comment by expez** [comment]
Spinner isn't installed.  The package manager cannot find `1.0`.  Where is spinner available?  I couldn't find a melpa recipe when I looked earlier.

**Comment by Malabarba** [comment]
It's on Gnu Elpa. I don't have a computer right now. Try checking if other gnu elpa packages are listed for you.

**Comment by expez** [comment]
That's it.  Nothing on gnu elpa gets past the firewall at work.  I'll just install manually on this machine.  Thanks!

**Comment by Malabarba** [comment]
Ah. It had to be a firewall. :-) 
Still, Paradox should not have been installed if the dependency failed. I'll have to look into that.
