### ISSUE TITLE
error in process sentinel: Invalid url response

### ISSUE THREAD

**Issue by kaushalmodi** [Malabarba/paradox#75]
Debug Backtrace:
 
I get the below error on doing `M-x paradox-list-packages`. 
This error is not seen if I don't require `paradox` and simply do `M-x package-list-packages`.

I am on the emacs master version built yesterday.

I started seeing this error probably since the past weekend.

Few odd things I noticed ever since this error started popping up; could be related?

- The stars column does not populate every time consistently; it's empty at times.
- Even if package upgrades are available, they did not show up. When I did `package-list-packages` and hit `U`, I saw I had few updates. But it could as well be that those updates got pushed in by the time I tried out `package-list-packages`. So just making a note of that here.

```
Debugger entered--Lisp error: (error "Invalid url response")
  signal(error ("Invalid url response"))
  error("Invalid url response")
  #[257 "\211@\306=\203 \307\302!\203 \302 \210\202\203 \310@AAA\"\210\202\203 eb\210\311\312\313\314#\204. \315\316!\210e`|\210\300A\300@\317 \320\321\322\"\"\320\301\"\323!<\203\201 \324\325\"\210\f\203Y \300
\235\203h \326\313\313\327%\210\330\300!\210\202\201 \331\301\302\332\333\334\335\336\300
$\337\"\340\341%%\210\266\342p!\207" [("gnu" . "http://elpa.gnu.org/packages/") "archive-contents" #[0 "\301\300!\207" [("gnu" . "http://elpa.gnu.org/packages/") package--update-downloads-in-progress] 2] package-user-dir package-check-signature package-unsigned-archives :error functionp signal search-forward "\n\n" nil noerror error "Invalid url response" buffer-string expand-file-name format "archives/%s" read-from-string make-directory t write-region silent package--update-downloads-in-progress package--check-signature make-byte-code 256 "\211\204 \f\305=\204 \306\300!\210\307\310\301\"\210\311\302\312\303\312\313%\210\211\203- \311\314\315\316#\312\303\317P\312\313%\210\306\300!\207" vconcat vector [package-check-signature allow-unsigned package--update-downloads-in-progress error "Unsigned archive `%s'" write-region nil silent mapconcat epg-signature-to-string "\n" ".signed"] 7 "\n\n(fn &optional GOOD-SIGS)" kill-buffer] 20 "\n\n(fn STATUS)"](nil)
  apply(#[257 "\211@\306=\203 \307\302!\203 \302 \210\202\203 \310@AAA\"\210\202\203 eb\210\311\312\313\314#\204. \315\316!\210e`|\210\300A\300@\317 \320\321\322\"\"\320\301\"\323!<\203\201 \324\325\"\210\f\203Y \300
\235\203h \326\313\313\327%\210\330\300!\210\202\201 \331\301\302\332\333\334\335\336\300
$\337\"\340\341%%\210\266\342p!\207" [("gnu" . "http://elpa.gnu.org/packages/") "archive-contents" #[0 "\301\300!\207" [("gnu" . "http://elpa.gnu.org/packages/") package--update-downloads-in-progress] 2] package-user-dir package-check-signature package-unsigned-archives :error functionp signal search-forward "\n\n" nil noerror error "Invalid url response" buffer-string expand-file-name format "archives/%s" read-from-string make-directory t write-region silent package--update-downloads-in-progress package--check-signature make-byte-code 256 "\211\204 \f\305=\204 \306\300!\210\307\310\301\"\210\311\302\312\303\312\313%\210\211\203- \311\314\315\316#\312\303\317P\312\313%\210\306\300!\207" vconcat vector [package-check-signature allow-unsigned package--update-downloads-in-progress error "Unsigned archive `%s'" write-region nil silent mapconcat epg-signature-to-string "\n" ".signed"] 7 "\n\n(fn &optional GOOD-SIGS)" kill-buffer] 20 "\n\n(fn STATUS)"] nil)
  url-http-activate-callback()
  url-http-end-of-document-sentinel(#<process elpa.gnu.org> "connection broken by remote peer\n")
  url-http-async-sentinel(#<process elpa.gnu.org> "connection broken by remote peer\n")
```

**Comment by Malabarba** [comment]
Hi kaushal. Sorry for the delay, I just got back from holiday.
Are you still having problem? 

I've been noticing this error occasional on a bot I run at work (though it hasn't happen to me yet), but so far it has elluded my grasp. Does this happen every time you run `paradox-list-packages`, or just occasionally?

**Comment by kaushalmodi** [comment]
Not a problem.

I'd say that this happens more often than not when using
paradox-list-packages.

-- 
Kaushal Modi

**Comment by Malabarba** [comment]
Is this on latest Emacs master?

**Comment by kaushalmodi** [comment]
Yes, I'll try it on 24.5 when I get a chance later today.

-- 
Kaushal Modi

**Comment by kaushalmodi** [comment]
Currently, I cannot get that error show up on both master build and 24.5.

**Comment by Malabarba** [comment]
Ok. I'll leave this issue open for now. This kind of thing is difficult to track down so it may take us a while. There are 2 things that could have triggered that. It's either a failure when accessing one of the package repos, or when accessing the star count on Github. This could be a proxy, a firewall, server downtime, or even just a bad connection.

Since you say it only happens with paradox, it's probably failing when accessing the star count. I'll push some changes to package.el that will make the error message more informative.

**Comment by Malabarba** [comment]
One thing I forgot to say. Whenever a url error occurs, package.el leaves behind an http buffer which could contain useful information. The buffer will be called something like: `*http ADDRESS*`. When this happens again, let me know the name and content of the buffer.

**Comment by kaushalmodi** [comment]
Will do, thanks.

**Comment by manuel-uberti** [comment]
I'm experiencing this issue at the moment. My Emacs build is ```e802250```. As usual, if you need to do some tests and/or debugging, feel free to ask.

**Comment by Malabarba** [comment]
When this error happens, there should be a buffer called something like: `*http ADDRESS*`. If you could paste here the contents of that buffer, it would be nice.

**Comment by manuel-uberti** [comment]
Actually, I just built Emacs trunk (```0fe5489```). Error appears to be gone. No ```*http ADDRESS*``` buffer either.

**Comment by Malabarba** [comment]
This is certainly the most elusive error I've ever not seen.

**Comment by manuel-uberti** [comment]
Ok, error is back today: Emacs build: ```dbc192b```, no ```*http ADDRESS*``` buffer though. Message is different though, should I open a new issue?
```error in process filter: peculiar error: 404 [2 times]```

**Comment by kaushalmodi** [comment]
@manuel-uberti I see the same thing too, latest emacs build, no \*http ADDRESS\* buffer

**Comment by manuel-uberti** [comment]
Yes, @kaushalmodi, me too when using ```M-x paradox-list-packages```.

**Comment by Malabarba** [comment]
I was just struggling with the "peculiar erro: 404" bug on package.el right now. It should be fixed on the current emacs build (pushed just a minute ago).
Let me know if you still have problems after rebuilding.

**Comment by manuel-uberti** [comment]
Looks like it is fixed. This is the relevant lines in ```*Messages*```:
```
Overriding package-menu--print-info with paradox--print-info
Overriding package-menu--print-info-simple with paradox--print-info
Overriding package-menu--generate with paradox--generate-menu
Overriding package-menu-mode with paradox-menu-mode
Overriding truncate-string-to-width with paradox--truncate-string-to-width
Importing package-keyring.gpg...done
No projects needed to be removed.
Package refresh done
```

**Comment by kaushalmodi** [comment]
I confirm the fix too on [this](http://git.savannah.gnu.org/cgit/emacs.git/commit/?id=711e14ddad7fb1e80a86c79e37a957929e8c01a3) build.

*Unrelated, but came up with [this helper function](https://github.com/kaushalmodi/.emacs.d/blob/3ae4200e2d561f084aa9c44e9547bf0158dd7403/setup-files/setup-misc.el#L146-L157) to jump to the commit page of user's current emacs build, and also copy the link to the kill-ring.*

**Comment by Malabarba** [comment]
Neat. :)
