### ISSUE TITLE
void defstuct

### ISSUE THREAD

**Issue by tollerm** [Malabarba/paradox#76]
Hi,
After last update of the paradox package I got "void function defstruct" when starting the emacs. The reason for this is  a line "(defstruct (spinner ( ...." in spinner-autoloads.el The trivial fix is to change "defstruct" to "cl-defstruct" in spinner.el. In this case an autogenerated autolad file will contain "cl-defstruct".
Regards, Toller

**Comment by Malabarba** [comment]
Hi there. What's your emacs version and how do you install paradox? 
The destruct should be defined by the cl package.

**Comment by tollerm** [comment]
My emacs version is 24.4.91.1. I've installed paradox through melpa (actually I've updated paradox through paradox:)). May be this is also useful information: I am using use-package to load the paradox. Clearly, during package initialization defstruct is not aliazed to cl-defstruct.

**Comment by Malabarba** [comment]
Ok thanks. I've pushed a change to spinner.el which should go live tomorrow. Let me know if that fixes this.

**Comment by tollerm** [comment]
Yes, now it works fine. Thank you for prompt fixing.
T.

**Comment by Malabarba** [comment]
No problem, happy to help.
