### ISSUE TITLE
package-selected-packages not updated in custom.el when installing packages asynchronously

### ISSUE THREAD

**Issue by kaushalmodi** [Malabarba/paradox#77]
I figured out why I didn't have certain packages in the `package-selected.packages` var.

I have paradox enabled by default and also I tend to install packages asynchronously. When I do that, the packages get installed fine but that package name is not updated in the `package-selected.packages` var in `custom.el`. So I will end up uninstalling needed packages on doing `package-autoremove`.

If when installing packages using paradox, I choose NOT to install asynchronously, the custom.el is updated fine.

**emacs 25.x from git master**

**Comment by Malabarba** [comment]
Thanks for the report. I've pushed a fix, but it relies on a change I just I pushed to Emacs master.
