### ISSUE TITLE
paradox--post-execute-star-unstar: Symbol's function definition is void: seq-difference

### ISSUE THREAD

**Issue by brunoqc** [Malabarba/paradox#78]
I get this error when upgrading packages.

```
Package `magit-20150525.1145' deleted.
Package `helm-20150607.2256' deleted.
Installed 2 packages, and Deleted 2 packages. See the buffer *Paradox Report* for more details.
paradox--post-execute-star-unstar: Symbol's function definition is void: seq-difference
```

GNU Emacs 24.5.1 (x86_64-w64-mingw32) of 2015-05-16 on KAEL

**Comment by Malabarba** [comment]
I've just pushed a fix for this. Should be on Melpa in an hour or so. Let me know if it works.

**Comment by azynheira** [comment]
I have the same issue. I assume its on melpa without an increased in version number, so melpa (no stable) repo correct?
Thanks

**Comment by Malabarba** [comment]
@azynheira Yes, it was on Melpa. I pushed a tag now so it shuld come up on stable too. Let me know if it works.

**Comment by brunoqc** [comment]
The fix seems to work for me.
