### ISSUE TITLE
'nil causes problems

### ISSUE THREAD

**Issue by sewkokot** [Malabarba/paradox#79]
'nil (quote nil) causes problems to `pcase' in this commit:
https://github.com/Malabarba/paradox/commit/a3fb32b2c3623a71d63918293fddcc637762e4c8

**Comment by Malabarba** [comment]
What problems are those? Are you sure you're not referring to the problems that were *fixed* by this commit?

**Comment by sewkokot** [comment]
I get this error:
paradox-execute.el:260:1:Error: Unknown upattern `(quote nil)'
removing the quote from 'nil works OK

**Comment by Malabarba** [comment]
Oh, I guess this must be version dependant, I'll have to cookup a fix. What's your emacs version?

**Comment by sewkokot** [comment]
GNU Emacs 24.5.1 (x86_64-w64-mingw32) of 2015-04-12 on KAEL

**Comment by Malabarba** [comment]
Thanks,I've pushed a fix. Let me know if it works.

**Comment by sewkokot** [comment]
The previous error disapeared however now since I have
  (setq paradox-execute-asynchronously nil)
paradox does not see this nil and asks me the asynchro question in the minibuffer.

**Comment by sewkokot** [comment]
Sorry wrong alert. Now it works. Simply after the error I disabled the (use-package paradox) and the rest of my paradox settings were skiped.

**Comment by Malabarba** [comment]
Great. You had me worried there for a moment. :-)
