### ISSUE TITLE
Trying to install packages leads to: Errors:   (wrong-number-of-arguments (1 . 1) 2)

### ISSUE THREAD

**Issue by endrebak** [Malabarba/paradox#80]
I get the message `See *Paradox Report* buffer`, but all it contains is the following. How do I start to debug this?
```
Package transaction finished. Sat Jul  4 22:04:50 2015
Errors:
  (wrong-number-of-arguments (1 . 1) 2)
```

**Comment by Malabarba** [comment]
Thanks for reporting this. Just a couple of questions. 

Is this sync or async? 
What version of emacs and paradox are you on?

**Comment by endrebak** [comment]
OS X Yosemite. 
Emacs 25.0.50.1.  
Paradox 20150611.645

I'm not certain about whether it was `async` or not, but acking the spacemacs files that use paradox for `sync` only returned `async` so it was probably `async`:

```
~/.emacs.d (master) $ ack sync spacemacs/extensions/paradox/**
spacemacs/extensions/paradox/paradox.el
103:;; 2.0   - 2014/12/13 - `paradox-menu-execute' can do asynchronous (background) operations.
329:(defcustom paradox-execute-asynchronously 'ask
330:  "Whether the install/delete/upgrade should be asynchronous.
547:`paradox-execute-asynchronously'. Optional argument NOQUERY
548:non-nil means do not ask the user to confirm. If asynchronous,
562:           (or (not paradox-execute-asynchronously)
563:               (and (eq 'ask paradox-execute-asynchronously)
564:                    (not (y-or-n-p "Execute in the background? (see `paradox-execute-asynchronously')")))))
577:    ;; Async execution
578:    (unless (require 'async nil t)
579:      (error "For asynchronous execution please install the `async' package"))
593:      ;; We have to do this with eval, because `async-start' is a
596:       `(async-start
669:If `paradox-execute-asynchronously' is non-nil, part of this
902:        (url-retrieve-synchronously paradox--star-count-url)
```

**Comment by Malabarba** [comment]
It looks like you have paradox-execute-asynchronously set to 'ask, so it should have asked you whether you wanted async execution (unless your custom options change that variable). 

I see you're on emacs 25, how recent is your build?

Also, If you call `C-h f` on package-install, what does it say on the line that specifies how to call the function? (I'm specifically looking for the number of arguments it takes).

**Comment by endrebak** [comment]
```
package-install is an interactive autoloaded compiled Lisp function in
`package.el'.

(package-install PKG)

Install the package PKG.
PKG can be a package-desc or the package name of one the available packages
in an archive in `package-archives'.  Interactively, prompt for its name.

[back]
```

**Comment by endrebak** [comment]
My emacs is from the 17 of dec, but it is still the HEAD in `homebrew` (OS X package manager) it seems. Perhaps I should try to downgrade from the bleeding edge version and get 24.4.

**Comment by Malabarba** [comment]
Just to clarify: Paradox is designed to support both 24.5 and the development version (master branch). So yes, you can use the bleeding edge. The problem here is that you are using a pretty old bleeding edge. ;-) A lot has changed since December.
