### ISSUE TITLE
Package not found cancels whole transaction.

### ISSUE THREAD

**Issue by minimal** [Malabarba/paradox#82]
Hi

I was trying to upgrade ~50 packages but the transaction stopped after encountering file not found. So I tried again without the not-found package (sx). Then another package wasn't found so it stopped without upgrading most packages. It would be nice if paradox tried to install everything and logged the errors at the end instead of failing at the first error.

Thanks

```
Package transaction finished. Sun Jul 19 13:08:41 2015
Errors:
  (file-error http://melpa.org/packages/sx-20150702.818.tar Not found)


Installed:
  ztree        20150702.1013
  with-editor  20150710.252
  use-package  20150622.1044
```

**Comment by Malabarba** [comment]
Thanks for the suggestion, I'll think about the best way to do that.
Meanwhile, whenever this happens you can probably just hit `r` to refresh and upgrade everything again.

**Comment by minimal** [comment]
Thanks for the tip. Whatever I was doing didn't refresh the packages immediately, but I managed eventually.
