### ISSUE TITLE
Overview of packages not visible in dark mode line. 

### ISSUE THREAD

**Issue by ReneFroger** [Malabarba/paradox#83]
When I call `M-x paradox-list-packages`, after a long waiting, I get the packages list. 

I notice I see the numbers of pacakges (Upgrade, new, installed, etc). But I don't see the description: 

![naamloos](https://cloud.githubusercontent.com/assets/5211845/8905932/9dfbeab4-346a-11e5-9134-a83e73409b44.png)

**Comment by Malabarba** [comment]
What's your color theme? And what do you see if you call `M-x describe-face` with `mode-line-buffer-id`?

**Comment by ReneFroger** [comment]
`M-x describe-face` with `mode-line-buffer-id` gives me the following:

     Face: mode-line-buffer-id (sample) (customize this face)
     
     Documentation:
     Face used for buffer identification parts of the mode line.
     
     Defined in `faces.el'.
     
                Family: unspecified
               Foundry: unspecified
                 Width: unspecified
                Height: unspecified
                Weight: bold
                 Slant: unspecified
            Foreground: unspecified
     DistantForeground: unspecified
            Background: unspecified
             Underline: unspecified
              Overline: unspecified
        Strike-through: unspecified
                   Box: unspecified
               Inverse: unspecified
               Stipple: unspecified
                  Font: unspecified
               Fontset: unspecified
               Inherit: sml/filename


SML/filename inherit his properties from sml/prefix > sml/global. My custom settings to SML: 


     (custom-set-faces
      ;; custom-set-faces was added by Custom.
      ;; If you edit it by hand, you could mess it up, so be careful.
      ;; Your init file should contain only one such instance.
      ;; If there is more than one, they won't work right.
      '(default ((t (:inherit nil :stipple nil :background "#141414" :foreground "#CEB67F" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 110 :width normal :foundry "outline" :family "Consolas"))))
      '(bold-italic ((t (:slant italic :weight bold))))
      '(highlight ((t (:background "gray40"))))
      '(highlight-symbol-face ((t (:background "gray25"))))
      '(sml/filename ((t (:inherit sml/prefix :foreground "#7e3e00" :weight bold))))
      '(sml/folder ((t (:inherit sml/global :foreground "dim gray" :weight normal))))
      '(sml/global ((t (:foreground "gray30" :inverse-video nil))))
      '(sml/line-number ((t (:inherit sml/modes :foreground "dim gray" :weight bold))))
      '(sml/modes ((t (:inherit sml/global :foreground "#820000"))))
      '(sml/prefix ((t (:inherit sml/global :foreground "#7e3e00"))))
      '(sml/process ((t (:inherit sml/prefix :foreground "black"))))
      '(sml/time ((t (:inherit sml/modes :foreground "dark goldenrod"))))
      '(sml/vc-edited ((t (:inherit sml/prefix :foreground "dark goldenrod")))))

I use a custom colorscheme. Would you be interested if I upload it?

**Comment by Malabarba** [comment]
Hm, ok, and what if you describe `paradox-mode-line-face`? What do you get?

> I use a custom colorscheme. Would you be interested if I upload it? 
Might not be necessary... We`ll see.

**Comment by ReneFroger** [comment]
Are you sure you spelled it correct? 

When I'm typing `M-x describe-face` and then typing `paradox-mode-line-face RET`, then I get `[No match]`. 

I installed Paradox today, by the way.

**Comment by Malabarba** [comment]
Do you have paradox open right now? The face only shows up after you've launched the package.

**Comment by ReneFroger** [comment]
Sorry, it gives me now the following: 

      Face: paradox-mode-line-face (sample) (customize this face)
      
      Documentation:
      Face used on the package's name.
      
      Defined in `paradox-menu.el'.
      
                 Family: unspecified
                Foundry: unspecified
                  Width: unspecified
                 Height: unspecified
                 Weight: normal
                  Slant: unspecified
             Foreground: black
      DistantForeground: unspecified
             Background: unspecified
              Underline: unspecified
               Overline: unspecified
         Strike-through: unspecified
                    Box: unspecified
                Inverse: unspecified
                Stipple: unspecified
                   Font: unspecified
                Fontset: unspecified
                Inherit: mode-line-buffer-id
      
      [back]


Not sure why the foreground is set on black, I never setted it on black. And the `mode-line-buffer-id` is brown. So it confuses me why `paradox-mode-line-face` is setted on black. I set it now to red, and everything is readable now. Thanks for helping me out, however not sure why this problem is caused. Probably you use a lighttoned modeline, instead a black one. :D

**Comment by Malabarba** [comment]
The function `paradox--update-mode-line` is supposed to set the foreground color of that face according to your mode-line. For some reason that didn't work for you. =/

**Comment by ReneFroger** [comment]
Does the face of `paradox-mode-line-face` currently exists?

When I configured it as following: 

    (custom-theme-set-faces
   [..]
    '(paradox-mode-line-face ((t (:inherit sml/global :foreground "dark goldenrod"))))

In my theme-configuration, I don't see the changes after restarting Emacs with the same theme. By the way, you can [find my theme here](http://pastebin.com/kgdEP4Dx).

**Comment by Malabarba** [comment]
I pushed a new version which should fix that problem, should be on Melpa in a couple of hours. Let me know if it works for you.

**Comment by ReneFroger** [comment]
After upgrading Paradox.., and restarted Emacs. 

No, unfortunately I have adjusted my mode line to very dark grey. When you see sharp, you see the words are black. But they're unreadable when you don't put your eyes close to the screen.

**Comment by Malabarba** [comment]
What do you get if you `(describe-face 'paradox-mode-line-face)`?

**Comment by ReneFroger** [comment]
Weird, now I get the right colors, even I had restarted Emacs earlier. So this bug seems solved by now, thanks Malabarba. 

Update/Installed/Total are now visible. Note that the "Loading" indicator is still black.

**Comment by Malabarba** [comment]
Paradox doesn't apply a face to the `loading` indicator, so it's probably using the `sml/process` face.

**Comment by ReneFroger** [comment]
Aha, thanks.
