### ISSUE TITLE
Don't "patch" paradox-menu-mode

### ISSUE THREAD

**Issue by wasamasa** [Malabarba/paradox#86]
The combination of

```elisp
;; We need package-menu-mode to be our parent, otherwise some
;; commands throw errors.  But we can't actually derive from it,
;; otherwise its initialization will screw up the header-format.  So
;; we "patch" it like this.
(put 'paradox-menu-mode 'derived-mode-parent 'package-menu-mode)
```

and

```elisp
;; Tough it may not look like it, this is totally necessary too.
(paradox--override-definition 'package-menu-mode 'paradox-menu-mode)
```

has a rather curious effect.  I've written code for Evil to intelligently determine whether a given mode has been derived from a more basic mode which also takes aliases into account.  The former is done via `(get mode 'derived-mode-parent)`, the latter with `(let ((definition (symbol-function mode))) (if (symbolp definition) definition mode))`. If this code hits `paradox-menu-mode`, it goes into an endless loop:

```elisp
;; (get 'paradox-menu-mode 'derived-mode-parent) ;=> package-menu-mode
;; (symbol-function 'package-menu-mode) ;=> paradox-menu-mode
```

Please don't do that. I don't care whether you derive from `package-menu-mode` and fix all the issues cropping up or write something from scratch (and use EPL?), but I'm pretty sure the current approach is a horrible hack that may work for you, but breaks anything assuming nothing tampers with symbol plists.

**Comment by Malabarba** [comment]
I noticed a discussion about this on irc, so I was already bracing myself for the bug report. 

I'll see if I can remove the second snippet you quoted, it was written a while ago and may not be necessary anymore. 

> but I'm pretty sure the current approach is a horrible hack that may work for you, but breaks anything assuming nothing tampers with symbol plists.

This horrible hack is how paradox was born, and you're the first one to complain, so let's take a breath. :-)

**Comment by Malabarba** [comment]
> I'll see if I can remove the second snippet you quoted, it was written a while ago and may not be necessary anymore.

Just checked, and the code is still necessary. Would it solve your problem if Paradox used `nadvice` instead of `defalias`, or does your code also take advices into account?

**Comment by wasamasa** [comment]
How exactly would the code change if you'd go for `nadvice`?

**Comment by Malabarba** [comment]
Instead of doing

    (fset 'package-menu-mode 'paradox-menu-mode)

it would do

    (advice-add 'package-menu-mode :override 'paradox-menu-mode)

**Comment by wasamasa** [comment]
Yes, that would work for me.

**Comment by Malabarba** [comment]
Done. Let me know if it works.

**Comment by wasamasa** [comment]
I'm sure it would, but I'm getting a probably unrelated error I'll open a new ticket for.

**Comment by jonathanchu** [comment]
![giphy](https://cloud.githubusercontent.com/assets/66164/9051217/8326f448-3a25-11e5-96c2-e8574abad543.gif)
