### ISSUE TITLE
[FIXED] paradox--print-info: Invalid function: (cell (assq :stars (package-desc-extras pkg-desc)))

### ISSUE THREAD

**Issue by brunoqc** [Malabarba/paradox#89]
When I run `paradox-list-packages` I get :
```
paradox--print-info: Invalid function: (cell (assq :stars (package-desc-extras pkg-desc)))
```

GNU Emacs 24.5.1 (x86_64-w64-mingw32) of 2015-05-16 on KAEL

**Comment by Malabarba** [comment]
Yes, it was a bug in a version I released yesterday and also fixed yesterday. Try reinstalling paradox.

**Comment by brunoqc** [comment]
I upgraded to `20150803.1742` the problem is gone. Thanks!

**Comment by Malabarba** [comment]
I'm going to leave this open for a couple of days so people can see it more easily.
