### ISSUE TITLE
paradox-list-packages: *invalid* in mode-line

### ISSUE THREAD

**Issue by manuel-uberti** [Malabarba/paradox#91]
I thik it is easier to explain it with a picture:

![2015-08-12-144400_1404x108_scrot](https://cloud.githubusercontent.com/assets/8199224/9224177/cc356912-4100-11e5-87aa-c106ae4b6995.png)

I see spinner.el got updated on MELPA, could it be related to that? I am on GNU Emacs 25.0.50.1, commit ```197f280```.

If you need me to do more tests or debugging, feel free to ask.

**Comment by Malabarba** [comment]
It could be related. Did you try restarting Emacs after the update?

**Comment by Malabarba** [comment]
Immediately after upgrading, I saw that `*invalid*` flash briefly on the mode-line every time I refreshed. But restarting Emacs seems to have fixed it.

**Comment by manuel-uberti** [comment]
Nope, doesn't work for me. I restarted and ```*invalid*``` is still there.

**Comment by Malabarba** [comment]
Do you always have that "Executing Transaction" String in there?
You weren't supposed to see that anymore.

**Comment by manuel-uberti** [comment]
Yes, still there.

**Comment by Malabarba** [comment]
Does the `*invalid*` show up all the time? Or just while refreshing? Or just while installing something?

**Comment by Malabarba** [comment]
(I've pushed a524a6e, see if it helps).

**Comment by manuel-uberti** [comment]
```*invalid*``` shows up all the time. I'll test your last commit soon.

**Comment by manuel-uberti** [comment]
Good, you latest commit fixed it. Thank you for your prompt fix.
