### ISSUE TITLE
Blinking \*invalid\* in mode-line

### ISSUE THREAD

**Issue by kaushalmodi** [Malabarba/paradox#92]
Hi,

I noticed today that I get a blinking \*invalid\* string in the mode-line where there used to be spinner.

The latest commit 3 hrs back fixes that?

I don't get that \*invalid\* if I use plain `package-list-packages` with `paradox` disabled.

**Comment by kaushalmodi** [comment]
Opened the issue too soon.. :)

That blinking \*invalid\* issue goes away after updating to that commit.

**Comment by Malabarba** [comment]
😁
