### ISSUE TITLE
Error while trying to read file system events

### ISSUE THREAD

**Issue by manuel-uberti** [Malabarba/paradox#94]
I see this error when calling ```paradox-list-packages```

![2015-09-04-113215_727x44_scrot](https://cloud.githubusercontent.com/assets/8199224/9680672/b3814594-52f8-11e5-9863-8f621901d6d7.png)

After a while (~30 seconds), the message disappears and I can upgrade or install new packages.

I don't know how to debug this message, but if you need me to do further tests, just ask. :)

**Comment by Malabarba** [comment]
Does emacs hang while you get that message? If so you could try `M-x toggle-debug-on-quit` and then hitting `C-g` when it happens.

**Comment by manuel-uberti** [comment]
This what I get in ```*Backtrace*```:
```
Debugger entered--Lisp error: (quit)
  redisplay_internal\ \(C\ function\)()
```

**Comment by Malabarba** [comment]
Hm. =/
What if you turn on `debug-on-error` instead?

**Comment by manuel-uberti** [comment]
Nothing happens. I mean, nothing in ```*Backtrace*```.

**Comment by Malabarba** [comment]
Googling around, I find something similar to that on this bug report of a few months ago: https://lists.gnu.org/archive/html/bug-gnu-emacs/2015-04/msg00993.html

The actual bug report was for something else, but it seems they bumped into your problem as part of debugging the original issue.

Try building emacs with `--with-file-notification=inotify` as they suggest there.

**Comment by manuel-uberti** [comment]
Nope, same message.

**Comment by Malabarba** [comment]
Have you tried it without paradox?
I'm starting to think it might be an emacs bug.

**Comment by manuel-uberti** [comment]
Just tried: same message. You may be nailed it: could be an Emacs bug. Should we close it here?

**Comment by Malabarba** [comment]
I guess so. :+1:
