### ISSUE TITLE
Wrong type argument: integerp, nil after "fnfc"

### ISSUE THREAD

**Issue by abo-abo** [Malabarba/paradox#97]
I've just updated to the latest version and wanted to try the filtering.  Pressing <kbd>fn</kbd> works fine, however after <kbd>fc</kbd> an error pops up and most of the paradox functions stop working. This is on Emacs 25.

I tried to debug this, but the origin of the error escapes me. Maybe it happens in a hook or something.

**Comment by Malabarba** [comment]
Maybe. Have you tried `toggle-debug-on-error`?

**Comment by abo-abo** [comment]
It's not very informative, also edebug fails before I can step into `paradox--generate-menu`:

```
Debugger entered--Lisp error: (wrong-type-argument integerp nil)
  paradox--generate-menu(nil t)
  apply(paradox--generate-menu (nil t))
  package-menu--generate(nil t)
  package-list-packages(nil)
  paradox-list-packages(nil)
  funcall-interactively(paradox-list-packages nil)
  call-interactively(paradox-list-packages record nil)
  command-execute(paradox-list-packages record)
```

**Comment by Malabarba** [comment]
Ok. I'm not sure why it happened, but I think I know where. I've added a safeguard so that it shouldn't.
