### ISSUE TITLE
Commit list of package doesn't work

### ISSUE THREAD

**Issue by cgcgcg** [Malabarba/paradox#98]
When I hit `l` in the package list, I only get the message 'Package nil is not a GitHub repo.'
It seems that `paradox--package-repo-list` is not populated..

**Comment by Malabarba** [comment]
Sorry for the silence. I wasn't able to reproduce this here. You're saying the value of your `paradox--package-repo-list` is an empty hash table?

**Comment by cgcgcg** [comment]
I just realized that something in my config must be off. I called `list-packages`, not `paradox-list packages`. If I call the latter, everything works as expected. It's weird though that some of paradox's features are enabled if I use `list-packages`..

Thank you for this great package!

**Comment by Malabarba** [comment]
No problem. Glad it's solved!
