### ISSUE TITLE
Feature Request: Sort packages by github stars.

### ISSUE THREAD

**Issue by jiegec** [Malabarba/paradox#99]
By the way, under a slow network, M-x paradox-list-packages requires about one minute to load. A ping packet to github needs about 500 msec.

**Comment by Malabarba** [comment]
Sorting by github stars is already possible. Just click on the star at the top (or type `S *`).

As for the slowness, try the following:

1. Unsinstall paradox
1. Restart Emacs
2. Do M-x list-packages

How long does it take? Is it more than 30 seconds?

**Comment by jiegec** [comment]
It takes 10 seconds to M-x lisk-packages withput paradox.

**Comment by jiegec** [comment]
And, i see it is installing rich-minority in the first launch of paradox-list-packages. I think this should be installed when M-x package-install paradox.

**Comment by Malabarba** [comment]
That's very strange. Firstly, paradox should never be install anything when you list packages. Secondly, paradox doesn't even depend on rich minority. 

It sounds like there's something strange in your configs interfering here. Maybe an advice or a hook.

**Comment by jiegec** [comment]
Hmm, uninstalling rich-minority and open paradox again and it does not install rich-minority again. That might be my config fault.
